#!/usr/bin/env bash

set -e

echo
echo "Installing gems locally"
echo "= = ="
echo

if [ ${RUBY:-on} = 'on' ]; then
  gemName=$(ls *.gemspec | sed -e 's/\.gemspec//' | grep $(basename $(realpath .) | sed -e 's/-/[-_]/g'))

  echo "Gemspec: $gemName.gemspsec"

  gemInfo=($(
    gem build $gemName.gemspec --output install-gems-installation.gem --quiet 2>/dev/null |
      sed -E -n 's/^[[:blank:]]*(Name|Version):[[:blank:]]*(.*)$/\2/p'
  ))
  gem="${gemInfo[0]}-${gemInfo[1]}"

  echo "Gem: $gem"
  echo

  cmd="gem install --no-document --install-dir ./gems --no-user-install --bindir ./gems/script --development install-gems-installation.gem"

  echo $cmd
  ($cmd)

  echo

  rm -vf install-gems-installation.gem

  ruby <<RUBY > ./gems/gems_init.rb
puts "# Generated by $0\n\n"
Dir['gems/gems/*'].each do |dir|
  dir = File.basename(dir)
  next if dir == "$gem"
  puts "\$LOAD_PATH.push('gems', File.join(__dir__, 'gems', \"#{dir}\", 'lib'))"
end
RUBY

  echo
  echo "Wrote ./gems/gems_init.rb"
fi

if [ ${MRUBY:-off} = 'on' ]; then
  export MRUBY_GEM_PATH=$(dirname $(realpath $0))
  export MRUBY_CONFIG=${MRUBY_CONFIG:-${MRUBY_GEM_PATH}/mruby_build_config.rb}

  echo "MRUBY_ROOT: ${MRUBY_ROOT:-(not set)}"
  echo "MRUBY_CONFIG: ${MRUBY_CONFIG:-(not set)}"
  echo "MRUBY_GEM_PATH: $MRUBY_GEM_PATH"
  echo

  pushd $MRUBY_ROOT

  rm -vf ./bin/*

  rake -m -j ${MRUBY_COMPILE_JOBS:-1}

  popd

  mkdir -p ./gems/bin
  cp -v $MRUBY_ROOT/bin/{bench-mruby,mruby-require} ./gems/bin
  if [ -d $MRUBY_ROOT/build/mrbtest ]; then
    cp -v $MRUBY_ROOT/build/mrbtest/bin/mrbtest ./gems/bin
  fi
fi

echo
echo "(done)"
echo "- - -"
echo
